[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 4
truncation_symbol = ""

[git_metrics]
disabled = false
added_style = "bold blue"
only_nonzero_diffs = true
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[rust]
format = "via [ğŸ¦€ $version](red bold)"
